### ISSUE TITLE
Helm configs for raw-spans-grouper are broken

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#165]
## Use Case

https://github.com/hypertrace/hypertrace-ingester/pull/91 in Hypertrace Ingester caused changes introduced a key `kafkaStreamsConfig` for configs like this: https://github.com/hypertrace/hypertrace-ingester/blob/main/raw-spans-grouper/helm/values.yaml#L86-L91

<img width="554" alt="Screenshot 2021-01-19 at 2 52 32 PM" src="https://user-images.githubusercontent.com/26570044/105014618-a5d07c00-5a66-11eb-98cb-9c4dce72205d.png">

But in `dev` mode of deployment we were overriding those configs using old key format which was this: https://github.com/hypertrace/hypertrace-ingester/blob/v0.3.0-main-patch/raw-spans-grouper/helm/values.yaml#L101-L108
<img width="554" alt="Screenshot 2021-01-19 at 2 53 22 PM" src="https://user-images.githubusercontent.com/26570044/105015162-42931980-5a67-11eb-821d-a5af827e3a1a.png">

This is causing raw-spans-grouper to fail with an error:
```
org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:412)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:297)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1296)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:766)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:624)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:551)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:510)
Caused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```

## Proposal
Update the `values.yaml` file [here](https://github.com/hypertrace/hypertrace/tree/main/kubernetes/clusters/dev) to use updated key as per latest code.

**Comment by JBAhire** [comment]
resolved by https://github.com/hypertrace/hypertrace/pull/164
