### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.http.MimeTypes

### ISSUE THREAD

**Issue by ashisht99x** [hypertrace/hypertrace#254]
## Use Case
*I am trying to run the setup locallly on an Apple M1 machine.

Here is the Exception before it fails:
```
hypertrace_1            | 2021-06-28 13:53:26.988 [Timer-1] INFO  o.h.s.HypertraceUIServerTimerTask - Exhausted maximum attempts [30] in checking bootstrapping status. Manually check the status of data service [pinot].
hypertrace_1            | Exception in thread "Timer-1" java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.http.MimeTypes
hypertrace_1            | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)
hypertrace_1            | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
hypertrace_1            | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
hypertrace_1            | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
hypertrace_1            | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
hypertrace_1            | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
hypertrace_1            | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
hypertrace_1            | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
hypertrace_1            | 	at org.eclipse.jetty.server.Server.start(Server.java:423)
hypertrace_1            | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
hypertrace_1            | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
hypertrace_1            | 	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
hypertrace_1            | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
hypertrace_1            | 	at org.hypertrace.service.HypertraceUIServer.start(HypertraceUIServer.java:91)
hypertrace_1            | 	at org.hypertrace.service.HypertraceUIServerTimerTask.run(HypertraceUIServerTimerTask.java:111)
hypertrace_1            | 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
hypertrace_1            | 	at java.base/java.util.TimerThread.run(Unknown Source)
```

Any idea into how to resolve this issue ?

**Comment by suddendust** [comment]
Can confirm, I have a M1 and faced the exact same issue.

**Comment by suddendust** [comment]
Entire stack trace:

`java.lang.ExceptionInInitializerError

at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:175)

at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)

at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)


at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)


at org.eclipse.jetty.server.Server.start(Server.java:423)


at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)


at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)


at org.eclipse.jetty.server.Server.doStart(Server.java:387)


at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)


at org.hypertrace.core.serviceframework.PlatformService.start(PlatformService.java:141)


at org.hypertrace.core.serviceframework.PlatformServiceLauncher.main(PlatformServiceLauncher.java:28)


Caused by: java.nio.charset.IllegalCharsetNameException: l;charset=iso-8859-1

at java.base/java.nio.charset.Charset.checkName(Charset.java:308)


at java.base/java.nio.charset.Charset.lookup2(Charset.java:482)

at java.base/java.nio.charset.Charset.lookup(Charset.java:462)

at java.base/java.nio.charset.Charset.forName(Charset.java:526)


at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:107)

at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:67)


... 12 more`
