### ISSUE TITLE
ManagedChannelImpl is not getting shutdown in bootstrap task

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/hypertrace#89]
During startup of hypertrace, we see below stack trace as INFO message,

```
| 2020-10-01 23:57:56.399 [GraphQLServlet-6] INFO  o.h.c.g.u.g.DefaultGrpcChannelRegistry - Creating new channel for localhost:9001
hypertrace              | Oct 01, 2020 11:57:56 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
hypertrace              | SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=14, target=localhost:9001} was not shutdown properly!!! ~*~*~*
hypertrace              |     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
hypertrace              | java.lang.RuntimeException: ManagedChannel allocation site
hypertrace              | 	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
hypertrace              | 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
hypertrace              | 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
hypertrace              | 	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
hypertrace              | 	at org.hypertrace.core.attribute.service.client.AttributeServiceClient.<init>(AttributeServiceClient.java:23)
hypertrace              | 	at org.hypertrace.core.attribute.service.client.AttributeServiceClient.<init>(AttributeServiceClient.java:27)
hypertrace              | 	at org.hypertrace.core.bootstrapper.BootstrapContext.<init>(BootstrapContext.java:17)
hypertrace              | 	at org.hypertrace.core.bootstrapper.BootstrapContext.buildFrom(BootstrapContext.java:23)
hypertrace              | 	at org.hypertrace.core.bootstrapper.BootstrapRunner.execute(BootstrapRunner.java:56)
hypertrace              | 	at org.hypertrace.service.BootstrapTimerTask.run(BootstrapTimerTask.java:76)
hypertrace              | 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
hypertrace              | 	at java.base/java.util.TimerThread.run(Unknown Source)
hypertrace              |
hypertrace              | Oct 01, 2020 11:57:56 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
hypertrace              | SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=16, target=localhost:9001} was not shutdown properly!!! ~*~*~*
hypertrace              |     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
hypertrace              | java.lang.RuntimeException: ManagedChannel allocation site
hypertrace              | 	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
hypertrace              | 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
hypertrace              | 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
hypertrace              | 	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
hypertrace              | 	at org.hypertrace.entity.type.service.client.EntityTypeServiceClient.<init>(EntityTypeServiceClient.java:30)
hypertrace              | 	at org.hypertrace.core.bootstrapper.BootstrapContext.<init>(BootstrapContext.java:18)
hypertrace              | 	at org.hypertrace.core.bootstrapper.BootstrapContext.buildFrom(BootstrapContext.java:23)
hypertrace              | 	at org.hypertrace.core.bootstrapper.BootstrapRunner.execute(BootstrapRunner.java:56)
hypertrace              | 	at org.hypertrace.service.BootstrapTimerTask.run(BootstrapTimerTask.java:76)
hypertrace              | 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
hypertrace              | 	at java.base/java.util.TimerThread.run(Unknown Source)
```
However, this is not affecting any functionality, can we stub this INFO message or shutdown channel cleanly.

**Comment by kotharironak** [comment]
looking into this.

**Comment by kotharironak** [comment]
This is the references
- https://github.com/grpc/grpc-java/pull/5283/files
- https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java#L62-L64

**Comment by kotharironak** [comment]
Closing this as fixed by above PRs.
